version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  task-service:
    build: ./task-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  log-service:
    build: ./log-service
    ports:
      - "3003:3003"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - auth-service
      - task-service
      - log-service
      - frontend
